# Generated by Django 6.0.2 on 2026-03-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefblog', '0003_alter_post_body_alter_post_cover_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
