# Generated by Django 6.0.2 on 2026-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefblog', '0005_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
