# Generated by Django 6.0.2 on 2026-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefblog', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Публичное имя'),
        ),
    ]
