# Generated by Django 6.0.2 on 2026-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefblog', '0008_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
